In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from joblib import load
import keras
from tensorflow.keras.layers import Layer

2025-01-14 16:18:07.551544: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-01-14 16:18:07.714367: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:479] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-01-14 16:18:07.796546: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:10575] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-01-14 16:18:07.797285: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1442] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-01-14 16:18:07.925714: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-01-14 16:18:08.806737: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/home/tensor/anaconda3/envs/tensor_check/lib/python3.11/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(

In [2]:
@keras.saving.register_keras_serializable(package="MyLayers")
class L2Normalization(Layer):
    def call(self, inputs):
        return tf.linalg.l2_normalize(inputs, axis=1)

custom_objects = {
    "L2Normalization": L2Normalization
}

In [3]:
model = tf.keras.models.load_model('../Models/my_model.keras',custom_objects=custom_objects)

2025-01-14 16:18:19.022562: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2025-01-14 16:18:19.190761: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2025-01-14 16:18:19.190806: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2025-01-14 16:18:19.195118: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2025-01-14 16:18:19.195165: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2025-01-14 16:18:19.195182: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2025-01-14 16:18:19.358821: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2025-01-14 16:18:19.358880: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2025-01-14 16:18:19.358887: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2019] Could not identify NUMA node of platform GPU id 0, defaulting to 0.  Your kernel may not have been built with NUMA support.
2025-01-14 16:18:19.358911: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2025-01-14 16:18:19.359407: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1928] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1767 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3050 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6

In [4]:
model.summary()

Model: "functional_6"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_12      │ (None, 14)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ input_layer_13      │ (None, 15)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_40 (Dense)    │ (None, 45)        │        675 │ input_layer_12[0… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_44 (Dense)    │ (None, 24)        │        384 │ input_layer_13[0… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_41 (Dense)    │ (None, 33)        │      1,518 │ dense_40[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_45 (Dense)    │ (None, 13)        │        325 │ dense_44[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_42 (Dense)    │ (None, 45)        │      1,530 │ dense_41[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_46 (Dense)    │ (None, 48)        │        672 │ dense_45[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_43 (Dense)    │ (None, 28)        │      1,288 │ dense_42[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_47 (Dense)    │ (None, 28)        │      1,372 │ dense_46[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ l2_normalization_12 │ (None, 28)        │          0 │ dense_43[0][0]    │
│ (L2Normalization)   │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ l2_normalization_13 │ (None, 28)        │          0 │ dense_47[0][0]    │
│ (L2Normalization)   │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dot_6 (Dot)         │ (None, 1)         │          0 │ l2_normalization… │
│                     │                   │            │ l2_normalization… │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 23,294 (91.00 KB)

 Trainable params: 7,764 (30.33 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 15,530 (60.67 KB)

In [5]:
user_scaler=load('../Models/UserScaler.joblib')
movie_scaler=load('../Models/MovieScaler.joblib')
rating_scaler=load('../Models/MinMaxRatingScaler.joblib')

In [10]:
user_scaler.feature_names_in_

array(['2.0', '22.0', '4.0', '3.95', '4.25', '0.0', '0.0.1', '4.0.1',
       '4.12', '4.0.2', '4.04', '0.0.2', '3.0', '4.0.3', '0.0.3', '3.88',
       '3.89'], dtype=object)

In [6]:
df = pd.read_csv("updated_api_data.csv")

In [19]:
dfUser=pd.read_csv("user_file_forApi.csv")

In [17]:
dfTemp=pd.read_csv("../Data/content_user_train.csv")

In [20]:
dfUser

,2.0,22.0,4.0,3.95,4.25,0.0,0.0.1,4.0.1,4.12,4.0.2,4.04,0.0.2,3.0,4.0.3,0.0.3,3.88,3.89
0,2,22,4,3.95,4.25,0,0,4,4.12,4,4.04,0,3,4,0,3.88,3.89
1,2,22,4,3.95,4.25,0,0,4,4.12,4,4.04,0,3,4,0,3.88,3.89
2,2,22,4,3.95,4.25,0,0,4,4.12,4,4.04,0,3,4,0,3.88,3.89
3,2,22,4,3.95,4.25,0,0,4,4.12,4,4.04,0,3,4,0,3.88,3.89
4,2,22,4,3.95,4.25,0,0,4,4.12,4,4.04,0,3,4,0,3.88,3.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
842,2,22,4,3.95,4.25,0,0,4,4.12,4,4.04,0,3,4,0,3.88,3.89
843,2,22,4,3.95,4.25,0,0,4,4.12,4,4.04,0,3,4,0,3.88,3.89
844,2,22,4,3.95,4.25,0,0,4,4.12,4,4.04,0,3,4,0,3.88,3.89
845,2,22,4,3.95,4.25,0,0,4,4.12,4,4.04,0,3,4,0,3.88,3.89
846,2,22,4,3.95,4.25,0,0,4,4.12,4,4.04,0,3,4,0,3.88,3.89

In [9]:
df

,imdbId,title,genres,6874,2003,3.9618320610687023,1,0,0.1,0.2,...,0.4,0.5,0.6,0.7,0.8,0.9,0.10,1.2,Image URL,imdb links
0,206275,Save the Last Dance (2001),Drama|Romance,4054,2001,2.843750,0,0,0,0,...,0,1,0,0,0,1,0,0,https://m.media-amazon.com/images/M/MV5BMTY1Zj...,https://www.imdb.com/title/tt0206275
1,209475,"Wedding Planner, The (2001)",Comedy|Romance,4069,2001,2.909091,0,0,0,0,...,0,0,0,0,0,1,0,0,https://m.media-amazon.com/images/M/MV5BNjMyMT...,https://www.imdb.com/title/tt0209475
2,212985,Hannibal (2001),Horror|Thriller,4148,2001,2.935897,0,0,0,0,...,0,0,0,1,0,0,0,1,https://m.media-amazon.com/images/M/MV5BYTk3NG...,https://www.imdb.com/title/tt0212985
3,239948,Saving Silverman (Evil Woman) (2001),Comedy|Romance,4149,2001,2.772727,0,0,0,0,...,0,0,0,0,0,1,0,0,https://m.media-amazon.com/images/M/MV5BOWRhZm...,https://www.imdb.com/title/tt0239948
4,231775,Down to Earth (2001),Comedy|Fantasy|Romance,4153,2001,2.416667,0,0,0,0,...,0,0,1,0,0,1,0,0,https://m.media-amazon.com/images/M/MV5BMGRjNj...,https://www.imdb.com/title/tt0231775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
842,5013056,Dunkirk (2017),Action|Drama|Thriller,174055,2017,3.423077,1,0,0,0,...,0,1,0,0,0,0,0,1,https://m.media-amazon.com/images/M/MV5BZWU5Zj...,https://www.imdb.com/title/tt5013056
843,1856101,Blade Runner 2049 (2017),Sci-Fi,176371,2017,3.805556,0,0,0,0,...,0,0,0,0,0,0,1,0,https://m.media-amazon.com/images/M/MV5BNzA1Nj...,https://www.imdb.com/title/tt1856101
844,2380307,Coco (2017),Adventure|Animation|Children,177765,2017,3.538462,0,1,1,1,...,0,0,0,0,0,0,0,0,https://m.media-amazon.com/images/M/MV5BMDIyM2...,https://www.imdb.com/title/tt2380307
845,2527336,Star Wars: The Last Jedi (2017),Action|Adventure|Fantasy|Sci-Fi,179819,2017,3.125000,1,1,0,0,...,0,0,1,0,0,0,1,0,https://m.media-amazon.com/images/M/MV5BMjQ1Mz...,https://www.imdb.com/title/tt2527336
846,5463162,Deadpool 2 (2018),Action|Comedy|Sci-Fi,187593,2018,3.875000,1,0,0,0,...,0,0,0,0,0,0,1,0,https://m.media-amazon.com/images/M/MV5BZWY1YW...,https://www.imdb.com/title/tt5463162

In [19]:
movie_scaler.feature_names_in_

array(['6874', '2003', '3.9618320610687023', '1', '0', '0.1', '0.2',
       '0.3', '1.1', '0.4', '0.5', '0.6', '0.7', '0.8', '0.9', '0.10',
       '1.2'], dtype=object)

In [37]:
vm=movie_scaler.transform(df.iloc[:,3:20])

In [21]:
vu=user_scaler.transform(dfUser)

In [43]:
type(vm)

numpy.ndarray

In [38]:
a=df.iloc[:,3:20]

In [39]:
a.iloc[:,2:]

,3.9618320610687023,1,0,0.1,0.2,0.3,1.1,0.4,0.5,0.6,0.7,0.8,0.9,0.10,1.2
0,2.843750,0,0,0,0,0,0,0,1,0,0,0,1,0,0
1,2.909091,0,0,0,0,1,0,0,0,0,0,0,1,0,0
2,2.935897,0,0,0,0,0,0,0,0,0,1,0,0,0,1
3,2.772727,0,0,0,0,1,0,0,0,0,0,0,1,0,0
4,2.416667,0,0,0,0,1,0,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
842,3.423077,1,0,0,0,0,0,0,1,0,0,0,0,0,1
843,3.805556,0,0,0,0,0,0,0,0,0,0,0,0,1,0
844,3.538462,0,1,1,1,0,0,0,0,0,0,0,0,0,0
845,3.125000,1,1,0,0,0,0,0,0,1,0,0,0,1,0
846,3.875000,1,0,0,0,1,0,0,0,0,0,0,0,1,0

In [36]:
df.iloc[:,[1,2,4,20]]

,title,genres,2003,Image URL
0,Save the Last Dance (2001),Drama|Romance,2001,https://m.media-amazon.com/images/M/MV5BMTY1Zj...
1,"Wedding Planner, The (2001)",Comedy|Romance,2001,https://m.media-amazon.com/images/M/MV5BNjMyMT...
2,Hannibal (2001),Horror|Thriller,2001,https://m.media-amazon.com/images/M/MV5BYTk3NG...
3,Saving Silverman (Evil Woman) (2001),Comedy|Romance,2001,https://m.media-amazon.com/images/M/MV5BOWRhZm...
4,Down to Earth (2001),Comedy|Fantasy|Romance,2001,https://m.media-amazon.com/images/M/MV5BMGRjNj...
...,...,...,...,...
842,Dunkirk (2017),Action|Drama|Thriller,2017,https://m.media-amazon.com/images/M/MV5BZWU5Zj...
843,Blade Runner 2049 (2017),Sci-Fi,2017,https://m.media-amazon.com/images/M/MV5BNzA1Nj...
844,Coco (2017),Adventure|Animation|Children,2017,https://m.media-amazon.com/images/M/MV5BMDIyM2...
845,Star Wars: The Last Jedi (2017),Action|Adventure|Fantasy|Sci-Fi,2017,https://m.media-amazon.com/images/M/MV5BMjQ1Mz...
846,Deadpool 2 (2018),Action|Comedy|Sci-Fi,2018,https://m.media-amazon.com/images/M/MV5BZWY1YW...

In [22]:
def load_dataset(scalerItem,scalerUser):
    # Load the CSV file
    df = pd.read_csv("updated_api_data.csv")
    dfUser=pd.read_csv("user_file_forApi.csv")
    item_train = scalerItem.transform(df.iloc[:,3:20])
    user_train= scalerUser.transform(dfUser)
    info=df.iloc[:,[1,2,4,20]]
    return [info,user_train[:,3:],item_train[:,2:]]

In [42]:
def predict():
    model.evaluate([,])

SyntaxError: expected '(' (3539049768.py, line 1)

In [ ]:
from flask import Flask, request, jsonify
import numpy as np
import tensorflow as tf  # Replace with the appropriate library for your model

app = Flask(__name__)

# Load your AI model (replace with your model's loading method)
# For demonstration, we'll create a mock model
class MockModel:
    def predict(self, input_data):
        # Mock prediction logic (replace with actual model prediction)
        return [x * 2 for x in input_data]  # Example: doubles each element

model = MockModel()

@app.route('/predict', methods=['POST'])
def predict():
    try:
        # Get JSON data from the request
        data = request.json
        if not data or 'input' not in data:
            return jsonify({'error': 'Invalid input. Please provide a list under the "input" key.'}), 400
        
        input_data = data['input']
        
        # Ensure the input is a list
        if not isinstance(input_data, list) or not all(isinstance(i, (int, float)) for i in input_data):
            return jsonify({'error': 'Input must be a list of numbers (e.g., [1, 2, 3]).'}), 400
        
        # Convert input data to the format your model expects
        input_array = np.array(input_data)

        # Get predictions from the model
        predictions = model.predict(input_array)

        # Return predictions as JSON
        return jsonify({'predictions': predictions})
    
    except Exception as e:
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    app.run(debug=True)

In [23]:
from flask import Flask, request, jsonify
# import numpy as np
# import tensorflow as tf  # Or the library you're using for your model

app = Flask(__name__)

# Load your pre-trained model
#model = tf.keras.models.load_model("path_to_your_model.h5")  # Update the path to your model file

@app.route('/predict', methods=['GET'])
def predict():
    try:
        # Parse the input JSON request
        #input_data = request.json.get("data")
        
        # Ensure input data is a valid numpy array
        # if input_data is None or not isinstance(input_data, list):
        #     return jsonify({"error": "Invalid input. Expected a list of numbers."}), 400
        
        # Convert input data to a NumPy array
        #input_array = np.array(input_data).reshape(1, -1)  # Adjust reshape based on model input requirements

        _,user_train,item_train=load_dataset(movie_scaler,user_scaler)
        
        # Make predictions using the model
        predictions = model.predict([user_train,item_train])
        
        # Convert predictions to a list
        predictions_list = predictions.flatten().tolist()  # Flatten if predictions are multi-dimensional
        
        # Format predictions as a list of JSON objects
        formatted_predictions = [{"prediction {}".format(i + 1): pred} for i, pred in enumerate(predictions_list)]
        
        # Return formatted predictions as a JSON object
        return jsonify(formatted_predictions)
    
    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    app.run(debug=True)

 * Serving Flask app '__main__'
 * Debug mode: on

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/tensor/anaconda3/envs/tensor_check/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/home/tensor/anaconda3/envs/tensor_check/lib/python3.11/site-packages/traitlets/config/application.py", line 1074, in launch_instance
    app.initialize(argv)
  File "/home/tensor/anaconda3/envs/tensor_check/lib/python3.11/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tensor/anaconda3/envs/tensor_check/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 654, in initialize
    self.init_sockets()
  File "/home/tensor/anaconda3/envs/tensor_check/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 331, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tensor/anaconda3/envs/tensor_check/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 253, in _bind_socket
    return self._try_bind_socket(s, port)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tensor/anaconda3/envs/tensor_check/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 229, in _try_bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "/home/tensor/anaconda3/envs/tensor_check/lib/python3.11/site-packages/zmq/sugar/socket.py", line 302, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 564, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use (addr='tcp://127.0.0.1:49983')

SystemExit: 1

/home/tensor/anaconda3/envs/tensor_check/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3585: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

In [28]:
import numpy as np
import pandas as pd

# Example DataFrame creation
data = np.random.rand(1, 14)  # Replace with your actual NumPy array
print(data)
columns = ['3.95', '4.25', '0.0', '0.0.1', '4.0.1',
           '4.12', '4.0.2', '4.04', '0.0.2', '3.0', '4.0.3', '0.0.3', '3.88', '3.89']
df = pd.DataFrame(data, columns=columns)
tempDf=pd.read_csv('temp_user_data.csv')
df=pd.concat([tempDf,df],axis=1)

# Replicate rows until the length is 847
replicated_df = pd.concat([df] * (847 // len(df)), ignore_index=True)  # Full replication
remaining_rows = 847 - len(replicated_df)  # Remaining rows to reach 847
if remaining_rows > 0:
    replicated_df = pd.concat([replicated_df, df.iloc[:remaining_rows]], ignore_index=True)

# Display the replicated DataFrame
print(replicated_df)
print(f"Length of DataFrame: {len(replicated_df)}")

[[0.65504898 0.43981543 0.32553218 0.31661412 0.26561121 0.19981429
  0.78870579 0.97848903 0.65146034 0.29122744 0.90147074 0.94621894
  0.46187095 0.03848016]]
     2.0  22.0  4.0      3.95      4.25       0.0     0.0.1     4.0.1  \
0      2    22    4  0.655049  0.439815  0.325532  0.316614  0.265611
1      2    22    4  0.655049  0.439815  0.325532  0.316614  0.265611
2      2    22    4  0.655049  0.439815  0.325532  0.316614  0.265611
3      2    22    4  0.655049  0.439815  0.325532  0.316614  0.265611
4      2    22    4  0.655049  0.439815  0.325532  0.316614  0.265611
..   ...   ...  ...       ...       ...       ...       ...       ...
842    2    22    4  0.655049  0.439815  0.325532  0.316614  0.265611
843    2    22    4  0.655049  0.439815  0.325532  0.316614  0.265611
844    2    22    4  0.655049  0.439815  0.325532  0.316614  0.265611
845    2    22    4  0.655049  0.439815  0.325532  0.316614  0.265611
846    2    22    4  0.655049  0.439815  0.325532  0.316614  0.265611

         4.12     4.0.2      4.04    0.0.2       3.0     4.0.3     0.0.3  \
0    0.199814  0.788706  0.978489  0.65146  0.291227  0.901471  0.946219
1    0.199814  0.788706  0.978489  0.65146  0.291227  0.901471  0.946219
2    0.199814  0.788706  0.978489  0.65146  0.291227  0.901471  0.946219
3    0.199814  0.788706  0.978489  0.65146  0.291227  0.901471  0.946219
4    0.199814  0.788706  0.978489  0.65146  0.291227  0.901471  0.946219
..        ...       ...       ...      ...       ...       ...       ...
842  0.199814  0.788706  0.978489  0.65146  0.291227  0.901471  0.946219
843  0.199814  0.788706  0.978489  0.65146  0.291227  0.901471  0.946219
844  0.199814  0.788706  0.978489  0.65146  0.291227  0.901471  0.946219
845  0.199814  0.788706  0.978489  0.65146  0.291227  0.901471  0.946219
846  0.199814  0.788706  0.978489  0.65146  0.291227  0.901471  0.946219

         3.88     3.89
0    0.461871  0.03848
1    0.461871  0.03848
2    0.461871  0.03848
3    0.461871  0.03848
4    0.461871  0.03848
..        ...      ...
842  0.461871  0.03848
843  0.461871  0.03848
844  0.461871  0.03848
845  0.461871  0.03848
846  0.461871  0.03848

[847 rows x 17 columns]
Length of DataFrame: 847